## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN V16 [get_ports {en}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {en}]
#set_property PACKAGE_PIN W16 [get_ports {o_level[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {o_level[1]}]
#set_property PACKAGE_PIN W17 [get_ports {number[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {number[0]}]
#set_property PACKAGE_PIN W15 [get_ports {number[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {number[1]}]
#set_property PACKAGE_PIN V15 [get_ports {number[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {number[2]}]
#set_property PACKAGE_PIN W14 [get_ports {number[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {number[3]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
##set_property PACKAGE_PIN W2 [get_ports {sw[12]}]					
#	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
##set_property PACKAGE_PIN U1 [get_ports {sw[13]}]					
#	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
##set_property PACKAGE_PIN T1 [get_ports {sw[14]}]					
#	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]

#Buttons
set_property PACKAGE_PIN U18 [get_ports button]                        
    set_property IOSTANDARD LVCMOS33 [get_ports button] 


#VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vga_red0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red0}]
set_property PACKAGE_PIN H19 [get_ports {vga_red0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red0}]
set_property PACKAGE_PIN J19 [get_ports {vga_red0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red0}]
set_property PACKAGE_PIN N19 [get_ports {vga_red0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red0}]
set_property PACKAGE_PIN N18 [get_ports {vga_blue0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue0}]
set_property PACKAGE_PIN L18 [get_ports {vga_blue0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue0}]
set_property PACKAGE_PIN K18 [get_ports {vga_blue0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue0}]
set_property PACKAGE_PIN J18 [get_ports {vga_blue0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue0}]
set_property PACKAGE_PIN J17 [get_ports {vga_green0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green0}]
set_property PACKAGE_PIN H17 [get_ports {vga_green0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green0}]
set_property PACKAGE_PIN G17 [get_ports {vga_green0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green0}]
set_property PACKAGE_PIN D17 [get_ports {vga_green0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green0}]
set_property PACKAGE_PIN P19 [get_ports vga_hsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]